project_identifier_env: CROWDIN_REACT_PROJECT_ID
api_key_env: CROWDIN_REACT_API_KEY
base_path: ./
preserve_hierarchy: 1
files:
  - source: /beta/src/content/learn/*.md
    translation: /beta/src/content/learn/%two_letters_code%/*.md
